nelmio_api_doc:
  documentation:
    info:
      title: Slipnote
      description: üî• –°–µ—Ä–≤–∏—Å –±—ã—Å—Ç—Ä—ã—Ö –∑–∞–º–µ—Ç–æ–∫
      version: 1.0.0
    servers:
      - url: 'http://%env(SERVER_NAME)%'
        description: 'Local —Å–µ—Ä–≤–µ—Ä (HTTP)'
    components:
      securitySchemes:
        Bearer:
          type: http
          scheme: bearer
          bearerFormat: JWT
    security:
      - Bearer: [ ]
    tags:
      - name: authorization
        description: '–û–ø–µ—Ä–∞—Ü–∏–∏ –∞–≤—Ç–æ—Ä–∏–∑–∞—Ü–∏–∏ –∏ –∞—É—Ç–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ü–∏–∏'
    paths:
      /api/login_check:
        post:
          tags:
            - authorization
          operationId: getJWT
          summary: –ü–æ–ª—É—á–∏—Ç—å JWT —Ç–æ–∫–µ–Ω
          description: –í—ã–ø–æ–ª–Ω–∏—Ç—å –∑–∞–ø—Ä–æ—Å –¥–ª—è –ø–æ–ª—É—á–µ–Ω–∏—è JWT —Ç–æ–∫–µ–Ω–∞
          security: []
          requestBody:
            content:
              application/json:
                schema:
                  type: object
                  required: [username, password]
                  properties:
                    username:
                      type: string
                      format: email
                      example: 'user@example.com'
                      description: 'Email –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—è'
                    password:
                      type: string
                      format: password
                      minLength: 6
                      example: 'password123'
                      description: '–ü–∞—Ä–æ–ª—å –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—è'
          responses:
            '200':
              description: –£—Å–ø–µ—Ö
              content:
                application/json:
                  schema:
                    type: object
                    required: [token]
                    properties:
                      token:
                        type: string
                        example: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3NjkyODk3NDEsImV4cCI6MTc2OTI5MzM0MSwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoidGVzdEBtYWlsLnJ1In0.LUkyfjl04qVQd1KLJonrtHnHx6Z6JwTpysYokH6TnWjToTxTXANXwqi9ukPSXRIqZYmGTCPie6lSs_Snc1nsN17uorK8mkatNdqdHd40Zzy9vTG5xkzcrreA8Z5hYoRDiCkuqs29M_pNW3I7nXXVCn3R8Fwug0ODG5RYdbgo-JkULOWJC6q6LwotqLTukU3w8kM8H0q2cdIJt5EhtfqOn1MjPrbe77ebfLxr2518XOj68g6h-G1_1R8MI25i_rNSUmZ9shImUyzDfv_KFY-xv5UWTzPuwsfOMm_AXWala7nB4qFRxP3QJAv08YckFU-4E5znW39m86PmIHISgTGaEQ'
                        description: '–¢–æ–∫–µ–Ω'
  html_config:
    swagger_ui_config:
      defaultModelsExpandDepth: 0 # —Å–≤–µ—Ä–Ω—É—Ç—å —Å—Ö–µ–º—ã
  areas: # to filter documented areas
    path_patterns:
      - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
